# Generated by Django 4.2.2 on 2024-06-12 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="cash",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="transfer_to_account",
        ),
        migrations.AddField(
            model_name="payments",
            name="type_of_payment",
            field=models.CharField(
                choices=[(1, "Оплата курса"), (2, "Оплата урока")],
                default=django.utils.timezone.now,
                max_length=150,
                verbose_name="Тип оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payments",
            name="date_of_payment",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата оплаты"
            ),
            preserve_default=False,
        ),
    ]
