# Generated by Django 4.2.2 on 2024-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payments_date_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="type_of_payment",
            field=models.CharField(
                choices=[("Наличные", "cash"), ("Карта", "card")],
                max_length=150,
                verbose_name="Тип оплаты",
            ),
        ),
    ]
