# Generated by Django 4.2.2 on 2024-07-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payments_type_of_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.TextField(blank=True, null=True, verbose_name="ID сессии"),
        ),
    ]
