# Generated by Django 4.2.2 on 2024-07-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_payments_date_of_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="created_ad",
        ),
    ]
