# Generated by Django 4.2.2 on 2024-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_payments_created_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="donate_url",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
