# Generated by Django 4.2.2 on 2024-06-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_course",
                    models.CharField(max_length=200, verbose_name="Название курса"),
                ),
                (
                    "preview_course",
                    models.ImageField(
                        upload_to="courses/", verbose_name="Превью курса"
                    ),
                ),
                ("description_course", models.TextField(verbose_name="Описание курса")),
                (
                    "created_at_course",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_lesson",
                    models.CharField(max_length=200, verbose_name="Название урока"),
                ),
                (
                    "preview_lesson",
                    models.ImageField(
                        upload_to="lessons/", verbose_name="Превью урока"
                    ),
                ),
                ("description_lesson", models.TextField(verbose_name="Описание урока")),
                ("link_to_video", models.URLField(verbose_name="Ссылка на видео")),
                (
                    "created_at_lesson",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания урока"
                    ),
                ),
                (
                    "courses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
