# Generated by Django 4.2.2 on 2024-06-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_preview_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="courses",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lessons",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
            ),
        ),
    ]
