# Generated by Django 4.2.2 on 2024-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="link_to_video",
        ),
        migrations.AddField(
            model_name="course",
            name="link_to_video_course",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link_to_video_lesson",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео урока"
            ),
        ),
    ]
