# Generated by Django 4.2.2 on 2024-07-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="title_course",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="title_lesson",
            new_name="title",
        ),
    ]
