# Generated by Django 4.2.2 on 2024-06-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_subscription_unique_together"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donate",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
            ),
        ),
    ]
